<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { dispatch } from '@/api/client'
import { useToast } from '@/composables/useToast'
interface Permission{id:number;name:string;description:string} interface Role{id:number;name:string;description:string;scope:string;permissions:string[];status:number}
const toast=useToast(),loading=ref(false),saving=ref(false),roles=ref<Role[]>([]),permissions=ref<Permission[]>([]),selected=ref<number|null>(null)
const form=reactive({roleId:null as number|null,name:'',description:'',scope:'ORGANISATION',permissionIds:[] as number[]})
async function load(){loading.value=true;try{const [r,p]=await Promise.all([dispatch<{results:Role[]}>('GET_ROLES'),dispatch<{results:Permission[]}>('GET_PERMISSIONS')]);roles.value=r.results??[];permissions.value=p.results??[];if(selected.value===null&&roles.value.length)edit(roles.value[0])}catch(e){toast.error(e instanceof Error?e.message:'Unable to load roles')}finally{loading.value=false}}
function edit(role:Role){selected.value=role.id;Object.assign(form,{roleId:role.id,name:role.name,description:role.description??'',scope:role.scope,permissionIds:permissions.value.filter(p=>role.permissions.includes(p.name)).map(p=>p.id)})}
function createRole(){selected.value=null;Object.assign(form,{roleId:null,name:'',description:'',scope:'ORGANISATION',permissionIds:[]})}
async function save(){saving.value=true;try{await dispatch('SAVE_ROLE',{...form});toast.success('Role saved');await load()}catch(e){toast.error(e instanceof Error?e.message:'Save failed')}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="admin-page"><header class="admin-head"><div><div class="title-row"><h1>Roles & permissions</h1><v-chip size="small" variant="tonal" color="primary">Anchor-wide policy</v-chip></div><p>Bundle capabilities into clear operational roles.</p></div><v-btn variant="outlined" prepend-icon="mdi-plus" @click="createRole">New role</v-btn></header>
 <div class="role-shell"><aside><button v-for="r in roles" :key="r.id" :class="{active:selected===r.id}" @click="edit(r)"><span>{{ r.name }}</span><small>{{ r.permissions.length }} permissions · {{ r.scope }}</small></button></aside>
 <v-card border flat class="editor"><v-card-text><div class="scope-band"><v-icon icon="mdi-shield-key-outline"/>This role controls access across your anchor.</div><div class="fields"><v-text-field v-model="form.name" label="Role name" variant="outlined"/><v-select v-model="form.scope" :items="['ANCHOR','ORGANISATION']" label="Scope" variant="outlined"/><v-textarea v-model="form.description" label="Description" variant="outlined" rows="2" class="wide"/></div><h2>Capabilities</h2><div class="permissions"><label v-for="p in permissions" :key="p.id"><v-checkbox-btn v-model="form.permissionIds" :value="p.id" color="primary"/><span><strong>{{ p.name.replaceAll('_',' ') }}</strong><small>{{ p.description }}</small></span></label></div></v-card-text><v-card-actions class="px-6 pb-6"><v-spacer/><v-btn color="primary" :loading="saving" @click="save">Save role</v-btn></v-card-actions></v-card></div>
</div></template>
<style scoped>
.admin-page{max-width:1200px;margin:auto}.admin-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.admin-head h1{font-size:2rem;letter-spacing:-.04em}.admin-head p{color:#64748b}.title-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.role-shell{display:grid;grid-template-columns:280px 1fr;gap:18px}aside{display:flex;flex-direction:column;gap:8px}aside button{text-align:left;background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:15px 16px;color:#334155}aside button.active{border-color:#14b8a6;background:#f0fdfa;box-shadow:inset 3px 0 #0d9488}aside span,aside small{display:block}aside span{font-weight:750}aside small{color:#64748b;margin-top:3px}.editor{border-radius:18px!important}.scope-band{display:flex;align-items:center;gap:9px;background:#ecfdf5;color:#115e59;margin:-16px -16px 24px;padding:12px 18px}.fields{display:grid;grid-template-columns:1fr 220px;gap:0 16px}.wide{grid-column:1/-1}h2{font-size:.82rem;text-transform:uppercase;letter-spacing:.1em;color:#475569;margin:8px 0 12px}.permissions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.permissions label{display:flex;gap:8px;border:1px solid #e2e8f0;border-radius:12px;padding:10px}.permissions strong,.permissions small{display:block}.permissions strong{font-size:.78rem}.permissions small{font-size:.75rem;color:#64748b;margin-top:3px}@media(max-width:800px){.role-shell{grid-template-columns:1fr}.permissions,.fields{grid-template-columns:1fr}.wide{grid-column:auto}.admin-head{align-items:flex-start;gap:14px;flex-direction:column}}
</style>
