package com.biopay.agent.face;

import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import android.util.Log;

import java.security.GeneralSecurityException;
import java.security.KeyStore;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * Encrypts the {@code faces.embedding} column at rest with a per-app, non-exportable
 * Android-Keystore AES key -- the "necessary migration" for the offline biometric store (see
 * DatabaseHelper's face table). The plaintext embedding never touches disk.
 *
 * <p>The actual AES-GCM encrypt/decrypt logic is a separate pair of package-private methods that
 * take a plain {@link SecretKey} rather than reaching into the Keystore themselves, specifically
 * so it can be unit-tested on a plain JVM (AndroidKeyStore is unavailable outside a device/
 * emulator) with a key generated by a normal {@link KeyGenerator} -- the cipher math is identical
 * either way, only where the key comes from differs.
 */
public final class FaceEmbeddingCipher {

    private static final String TAG = "FaceEmbeddingCipher";
    private static final String KEYSTORE_PROVIDER = "AndroidKeyStore";
    private static final String KEY_ALIAS = "biopay_face_embedding_key";
    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final int GCM_TAG_BITS = 128;
    private static final int GCM_IV_BYTES = 12;

    private FaceEmbeddingCipher() { }

    /** {@link KeyGenParameterSpec} (Keystore-backed symmetric keys) is available on every device
     *  this app runs on now that minSdk is 24 -- kept as a method (rather than inlined at call
     *  sites) so FaceDao's plaintext-fallback branch stays a single well-named check. */
    public static boolean isSupported() {
        return true;
    }

    /** @return Base64(iv || ciphertext+tag), or null if encryption fails -- callers must handle
     *  that by storing plaintext and marking the row as such. */
    public static String encrypt(String plaintext) {
        try {
            byte[] combined = encryptWithKey(getOrCreateKey(), plaintext.getBytes("UTF-8"));
            return Base64.encodeToString(combined, Base64.NO_WRAP);
        } catch (GeneralSecurityException | java.io.UnsupportedEncodingException ex) {
            Log.e(TAG, "Encryption failed, caller must fall back to plaintext storage: " + ex.getMessage());
            return null;
        }
    }

    public static String decrypt(String base64CipherText) {
        try {
            byte[] combined = Base64.decode(base64CipherText, Base64.NO_WRAP);
            return new String(decryptWithKey(getOrCreateKey(), combined), "UTF-8");
        } catch (GeneralSecurityException | java.io.UnsupportedEncodingException | IllegalArgumentException ex) {
            throw new IllegalStateException("Failed to decrypt stored face embedding", ex);
        }
    }

    // ---- Pure crypto core, testable with any SecretKey ----------------------------------------

    static byte[] encryptWithKey(SecretKey key, byte[] plaintext) throws GeneralSecurityException {
        Cipher cipher = Cipher.getInstance(TRANSFORMATION);
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] iv = cipher.getIV();
        byte[] ciphertext = cipher.doFinal(plaintext);
        byte[] combined = new byte[iv.length + ciphertext.length];
        System.arraycopy(iv, 0, combined, 0, iv.length);
        System.arraycopy(ciphertext, 0, combined, iv.length, ciphertext.length);
        return combined;
    }

    static byte[] decryptWithKey(SecretKey key, byte[] combined) throws GeneralSecurityException {
        if (combined.length < GCM_IV_BYTES) {
            throw new GeneralSecurityException("Ciphertext too short to contain an IV");
        }
        byte[] iv = new byte[GCM_IV_BYTES];
        System.arraycopy(combined, 0, iv, 0, GCM_IV_BYTES);
        byte[] ciphertext = new byte[combined.length - GCM_IV_BYTES];
        System.arraycopy(combined, GCM_IV_BYTES, ciphertext, 0, ciphertext.length);

        Cipher cipher = Cipher.getInstance(TRANSFORMATION);
        cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(GCM_TAG_BITS, iv));
        return cipher.doFinal(ciphertext);
    }

    // ---- Android Keystore key management -------------------------------------------------------

    private static SecretKey getOrCreateKey() throws GeneralSecurityException {
        try {
            KeyStore keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER);
            keyStore.load(null);
            KeyStore.SecretKeyEntry existing = (KeyStore.SecretKeyEntry) keyStore.getEntry(KEY_ALIAS, null);
            if (existing != null) {
                return existing.getSecretKey();
            }
            KeyGenerator generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER);
            generator.init(new KeyGenParameterSpec.Builder(KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    // Never exportable off-device; regenerating on Keystore loss (factory reset,
                    // key invalidation) is acceptable here since embeddings are re-enrollable from
                    // the beneficiary in person, unlike e.g. a password.
                    .build());
            return generator.generateKey();
        } catch (java.io.IOException | java.security.cert.CertificateException
                | java.security.NoSuchAlgorithmException | java.security.UnrecoverableEntryException ex) {
            throw new GeneralSecurityException("Unable to access Android Keystore", ex);
        }
    }
}
